services:
  app:
    build:
      dockerfile: ./Dockerfile.dev
    env_file:
      - bitwarden.env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    entrypoint: ./entrypoint.sh
